### ISSUE TITLE
Universal sourcemap generator library?

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-sourcemap#13]
I refactored the sourcemap generators into a file (at https://github.com/gulpjs/vinyl-sourcemap/blob/master/lib/generate.js) but that feels like it should be a separate library.

Does something like that already exist?  If not and we want to create a library, what should it look like?  I'm thinking it should look something like https://github.com/js-cli/js-interpret and require users to explicitly install the sourcemap generating libraries.

/cc @jonschlinkert @doowb @contra

**Comment by jonschlinkert** [comment]
Seems like something that would be useful as a separate lib. But my experience with sourcemaps is somewhat limited, so I'm not sure what a good API would look like for a sourcemaps lib.

**Comment by yocontra** [comment]
I don't think it should be split apart too much, there's only sourcemaps supported for a handful of files (html, css, js). A separate module makes sense for sourcemap generation, but then splitting it into a parent module where every type of sourcemap is another module is just overengineering.

**Comment by doowb** [comment]
Since it looks like the only place that is determining which sourcemap generator to use is [here](https://github.com/gulpjs/vinyl-sourcemap/blob/master/lib/helpers.js#L140-L147), I think that `vinyl-sourcemap` can add a `.register` or `.generator` method that allows registering sourcemap generators by extension. Then the defaults for `.js` and `.css` can be split into a module that's imported back into this library and set as defaults. This will let users create their own generators for different extensions and/or override the defaults by registering a different one for `.js` or `.css`.

I think this provides flexibility without make the code overly complex.

**Comment by phated** [comment]
The couple reasons I wanted something like `js-interpret` are:
1. The sourcemap-generating libraries are pretty hefty and are now going to be pulled in by vinyl-fs/gulp
2. There should be a way for users to remap extensions or generate sourcemaps for files being read by `gulp.src`, even if they aren't .js or .css files (the only 2 supported extensions currently).

@contra it wouldn't be separate modules, just a choose-your-own parser; very similar to how gulpfiles can be processed by one of many typescript modules depending on what the user installs alongside.  In my scenario, you'd run `npm install gulp acorn` but if you wanted esprima or something, you would just install `esprima` instead of acorn.

@doowb I don't think that would work because `vinyl-sourcemap` is consumed by module authors, instead of by end-users.  The way `js-interpret` handles this is by providing a singleton that anyone can mutate, effecting others up the dependency tree.

**Comment by yocontra** [comment]
@phated I'm fine with things being swappable if it adds something, but it should be optional and not a major distraction to the users or a PITA to maintain.

Not sure how swapping esprima/acorn is going to be best for the users, would appreciate some info there. IMO we should just pick the best one and remove yet another choice from our users plates.

**Comment by phated** [comment]
No need for this!  I broke the sourcemap generating code into https://github.com/gulp-sourcemaps/identity-map
