### ISSUE TITLE
Remove async

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-sourcemap#23]
Replace with smaller deps.  We only use 2 methods.

**Comment by phated** [comment]
cc @stevelacy - If you have some time and want to help

**Comment by stephenlacy** [comment]
I was looking at this one, I replaced one on my local branch but did not find a good replacement for the `applyEachSeries`

**Comment by phated** [comment]
Yeah, I vaguely remember thinking I'd need to create a replacement module.  I'd need to review to remember everything but I think there could be a better way to implement than `applyEachSeries`

**Comment by phated** [comment]
Wrapping this up now.  I found a good way to replace it with `now-and-later` which allows me to reduce the dependency tree even further
