### ISSUE TITLE
detect-newline

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-sourcemap#3]
While writing tests, I noticed that if I didn't have a newline specified in the `contents` Buffer, the value `null` was prepended and appended to the sourcemap.  There should probably be a default (maybe that can be upstreamed).

**Comment by robvenn** [comment]
This is probably because `detect-newline` returns null, and then indeed the `commentFormatter` in the `write`method wraps that, it could be `\n` as a default instead of `null`, or perhaps an empty string makes more sense.

**Comment by phated** [comment]
Yeah, this was a bug that crept into a gulp-sourcemaps release also.

**Comment by phated** [comment]
Switched to file-normalize so this is no longer an issue.
