### ISSUE TITLE
How to specify the `sourceRoot`?

### ISSUE THREAD

**Issue by ehmicky** [gulpjs/vinyl-sourcemap#34]
The following Gulp task:

```js
const gulpBabel = require('gulp-babel')

const babel = () => src('src/**', { sourcemaps: true })
  .pipe(gulpBabel({}))
  .pipe(dest('dist', { sourcemaps: '.' }))
```

Results in source maps like `dist/events.js.map`

```json
{
  "version":3,
  "sources":["events.js"],
  "names":["skipped for the example"],
  "mappings":"AAAA;;skipped for the example",
  "sourcesContent":["'use strict'\n\nskipped for the example"],
  "file":"events.js"
}
```

I think this source map is wrong because it's missing the location of the source directory, either by using `"sourceRoot": "../src"` or `"source": ["../src/events.js"]`. Because of this, it is not possible to locate the source files from just using the source maps. This ultimately led to issues for me like test coverage not working anymore.

It seems to me that the relative path from the built file to the source file is unknown until the end of the Gulp pipeline, i.e. until `vinyl-sourcemap.write()` is executed.

It is possible to work around the issue by using other modules like `gulp-sourcemaps`, but it would be nice to be able to fix this without their help.

**Comment by phated** [comment]
I believe you need this: https://github.com/gulp-sourcemaps/map-sources

**Comment by ehmicky** [comment]
Yes this works, thanks!

The final code for anyone interested:

```js
const gulpBabel = require('gulp-babel')
const mapSources = require('@gulp-sourcemaps/map-sources')

const babel = () => src('src/**', { sourcemaps: true })
  .pipe(gulpBabel({}))
  .pipe(mapSources(path => `../src/${path}`))
  .pipe(dest('dist', { sourcemaps: '.' }))
```
