### ISSUE TITLE
callback/return early when contents is not a buffer

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-sourcemap#4]
I noticed a weird error that took me awhile to track down: my original tests had `null` as the file contents, which was causing this module to throw.  It should probably just callback successfully if `!file.isBuffer()`

**Comment by robvenn** [comment]
Do you mean for the `add` method or for `write`? 
I've also noticed that the `!File.isVinyl(file)` error callback should probably come before everything else.

**Comment by phated** [comment]
This would have been for the `.add` method.  We should probably check `isVinyl` and `isBuffer` before everything.

**Comment by phated** [comment]
I think this was solved by #7 also
