### ISSUE TITLE
Transfer to gulp org to collaborate more easily?

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-sourcemap#6]
I was just wondering if you'd like to transfer this to the gulp org so we could get some more movement on it (by myself and the rest of the community).  Thoughts?

**Comment by robvenn** [comment]
Sure, I'll do this first, which will hopefully speed up development. Apologies for not responding sooner, didn't see these issues.

**Comment by robvenn** [comment]
@phated I can't transfer it directly to the gulp org, but I can transfer it to you and then you can transfer it to gulpjs.

**Comment by phated** [comment]
@robinvenneman thanks!  I've kept you on as a contributor also.
