### ISSUE TITLE
Use path.posix API

### ISSUE THREAD

**Issue by ghost** [gulpjs/vinyl-sourcemap#8]
Just FYI:

In https://github.com/gulpjs/vinyl-sourcemap/blob/master/index.js, if you change
```js
var path = require('path');
```
to
```js
var path = require('path').posix;
```
, you shouldn't need the `unixStylePath` function, as `path` should always use forward slashes.

https://nodejs.org/api/path.html#path_path_posix

**Comment by phated** [comment]
That's not supported in old node versions.

**Comment by ghost** [comment]
@phated "Added in: v0.11.15"  How old are we talking?

**Comment by phated** [comment]
We support 0.10.
