### ISSUE TITLE
Migrate test harness from tape to mocha/expect

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-sourcemap#9]
Tape: https://www.npmjs.com/package/tape
Mocha: https://www.npmjs.com/package/mocha and https://github.com/mjackson/expect
Example of how we write Mocha/Expect tests: https://github.com/gulpjs/glob-stream/blob/master/test/index.js

**Comment by CKGrafico** [comment]
Can you add why this decision to the issue? Only to know it. Personally I've moved from mocha to tape.

**Comment by phated** [comment]
Finished by #11
